//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metaclassification.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metaclassification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	
        ///1	1	1	1	0	1	0	0	1	1	1	1	1	1	1	1	1	1	1	1	1	0	0	1	1	0	1	0	1	1	1	1	1	1	1	1	1	1	1	1	
        ///1	1	1	1	1	1	1	0	0	1	0	0	0	1	0	1	0	0	0	0	0	1	0	0	0	1	0	0	0	0	0	0	1	0	1	1	0	0	0	0	
        ///1	1	1	1	1	1	1	1	1	1	1	1	0	1	1	0	1	1	0	0	1	0	0	1	0	0	1	1	0	0	0	0	0	0	0	0	1	0	1	1	
        ///1	0	1	1	1	1	1	1	1	1	0	0	1	1	1	0	1	0	0	1	1	0	0	1	0	0	1	1	0	1	1	1	0	0	1	1	1	1	0	0	
        ///1	1	0	1	0	1	1	1	1	1	0	0	1	0	0	0	0	0	1	0	0	1	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	
        ///1	1	1	0	1	0	1	1	1	1	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ain {
            get {
                return ResourceManager.GetString("Ain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2	e	10	205	101	178	1,859225885	94,9210198	133	158	431	163	1,554019378	298,0419434	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	46,708	17,2626765	-0,174672199	10,48528137	8,914900169	164,708	0,853502582	0,948728648	0,703734023	0,838888564	Infinity	1,105422819	1,021542994	1,64637227	0,607396042	159	139	24,384	10,29563014	1,063697822	4	5,14781507	47,384	0,761361567	1,001455565	0,5691621	0,754428327	Infinity	1,230753247	1,042569201	2,573907535	0,388514345	144	151	65,112	27,20294102	1,272297395	12,48528137	13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	0	1	1	0	1	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	0	1	1	0	0	1	1	1	0	0	1	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1	0	1	0	1	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	1	1	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	0	1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	0	1	0	1	1	0	0	0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RinAvg {
            get {
                return ResourceManager.GetString("RinAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	0	1	1	1	1	1	1	1	1	0	1	0	0	1	0	0	1	1	1	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	0	1	1	1	0	1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	1	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	0	0	1	1	1	1	1	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	1	1	1	1	1	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	0	0	1	0	1	1	0	1	0	0	1	0	0	1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RinGeom {
            get {
                return ResourceManager.GetString("RinGeom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	0	1	1	1	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	1	1	1	0	1	1	1	1	1	1	1	0	0	0	0	0	0	0	0	0	1	1	1	0	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	1	0	1	0	1	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	0	1	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	1	1	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	0	1	1	1	0	1	1	1	1	1	1	1	0	1	0	1	1	1	1	0	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	1	1	1	0	1	0	1	0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RinHarm {
            get {
                return ResourceManager.GetString("RinHarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	0	1	0	1	1	1	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	0	0	1	1	1	0	0	1	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	0	1	1	1	0	0	0	0	0	1	0	1	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	0	1	1	0	0	0	1	1	0	0	0	0	1	0	0	1	1	1	0	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	0	0	0	0	0	0	0	0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RinMed {
            get {
                return ResourceManager.GetString("RinMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	0	1	0	1	1	1	0	0	1	0	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	0	1	1	1	1	1	1	1	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	0	1	1	1	0	0	0	1	0	1	1	1	1	1	0	0	0	0	0	0	0	0	0	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	1	1	1	0	1	1	0	0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RinMinMax {
            get {
                return ResourceManager.GetString("RinMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	0	1	1	0	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	0	0	1	1	1	0	0	1	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	1	1	1	0	1	1	1	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	1	1	0	0
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	1	1	1
        ///-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	1	0	1	0	1	1	1	1	0	1	1	1	0	1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RinNegyz {
            get {
                return ResourceManager.GetString("RinNegyz", resourceCulture);
            }
        }
    }
}
